Importe o pacote pandas como o nome pd.

In [ ]:
import pandas as pd

Carregue em memória o conjunto de dados disponível na pasta data/anatel_mg_2006_2019.csv para uma variável chamada df.

In [ ]:
df = pd.read_csv('/content/dataanatel_mg_2006_2019.csv.txt')
df

,DataExtracao,Ano,Mes,CanalEntrada,Condicao,GrupoEconNorm,Tipo,Servico,Modalidade,Motivo,UF,QtdeSolic
0,2016-04-28,2006,1,Atendimento Pessoal,Nova,Anatel,Denúncia,Radiodifusão (Rádio e TV),Rádio FM,Interferência,MG,3
1,2016-04-28,2006,1,Atendimento Pessoal,Nova,Anatel,Denúncia,Radiodifusão (Rádio e TV),Rádio FM,Outorga,MG,8
2,2016-04-28,2006,1,Atendimento Pessoal,Nova,NET,Reclamação,Serviço Telefônico Fixo Comutado - STFC,Local,Cobrança,MG,1
3,2016-04-28,2006,1,Atendimento Pessoal,Nova,OI,Reclamação,Móvel Pessoal,Pós-Pago,Serviços Adicionais,MG,1
4,2016-04-28,2006,1,Atendimento Pessoal,Nova,Outros,Reclamação,Móvel Pessoal,Pós-Pago,Clonagem,MG,1
...,...,...,...,...,...,...,...,...,...,...,...,...
509701,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Celular Pré-Pago,Bloqueio ou Suspensão e Desbloqueio,Não consegue desbloquear aparelho,MG,1
509702,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Celular Pré-Pago,Portabilidade,Portabilidade recusada pela prestadora,MG,1
509703,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Celular Pré-Pago,"Qualidade, Funcionamento e Reparo",Não funcionamento de facilidade ou serviço adi...,MG,1
509704,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Telefone Fixo,Cancelamento,Cancelamento de serviço adicional não efetuado,MG,1
509705,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Telefone Fixo,"Qualidade, Funcionamento e Reparo",Linha muda ou sem sinal,MG,1

Quantas linhas e quantas colunas foram carregadas em memória?

In [ ]:
print(f'Número de linhas: {df.shape[0]}')
print(f'Número de colunas: {df.shape[1]}')

Número de linhas: 509706
Número de colunas: 12

Mostre as 5 primeiras linhas do dataset.

In [ ]:
df.loc[0:4,:]

,DataExtracao,Ano,Mes,CanalEntrada,Condicao,GrupoEconNorm,Tipo,Servico,Modalidade,Motivo,UF,QtdeSolic
0,2016-04-28,2006,1,Atendimento Pessoal,Nova,Anatel,Denúncia,Radiodifusão (Rádio e TV),Rádio FM,Interferência,MG,3
1,2016-04-28,2006,1,Atendimento Pessoal,Nova,Anatel,Denúncia,Radiodifusão (Rádio e TV),Rádio FM,Outorga,MG,8
2,2016-04-28,2006,1,Atendimento Pessoal,Nova,NET,Reclamação,Serviço Telefônico Fixo Comutado - STFC,Local,Cobrança,MG,1
3,2016-04-28,2006,1,Atendimento Pessoal,Nova,OI,Reclamação,Móvel Pessoal,Pós-Pago,Serviços Adicionais,MG,1
4,2016-04-28,2006,1,Atendimento Pessoal,Nova,Outros,Reclamação,Móvel Pessoal,Pós-Pago,Clonagem,MG,1

Quais são os tipos de dados de cada uma das colunas?

In [ ]:
df.dtypes

DataExtracao     object
Ano               int64
Mes               int64
CanalEntrada     object
Condicao         object
GrupoEconNorm    object
Tipo             object
Servico          object
Modalidade       object
Motivo           object
UF               object
QtdeSolic         int64
dtype: object

Mostre a quantidade de colunas para cada um dos tipos de dados.

In [ ]:
df.dtypes.value_counts()

object    9
int64     3
dtype: int64

Mostre as informações básicas do DataFrame.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 509706 entries, 0 to 509705
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   DataExtracao   509706 non-null  object
 1   Ano            509706 non-null  int64
 2   Mes            509706 non-null  int64
 3   CanalEntrada   509706 non-null  object
 4   Condicao       509706 non-null  object
 5   GrupoEconNorm  509404 non-null  object
 6   Tipo           509706 non-null  object
 7   Servico        509706 non-null  object
 8   Modalidade     509706 non-null  object
 9   Motivo         509706 non-null  object
 10  UF             509706 non-null  object
 11  QtdeSolic      509706 non-null  int64
dtypes: int64(3), object(9)
memory usage: 46.7+ MB

Verifique se existem dados ausentes (misssing data) no conjunto de dados.

In [ ]:
print('Existem valores ausentes!') if df.isnull().values.any() else print('Não existem valores ausentes no dataframe.')

Existem valores ausentes!

Qual é o número total de dados ausentes?

In [ ]:
df.isnull().sum().sum()

302

Qual é o número total de dados ausentes por coluna?

In [ ]:
df.isna().sum()

DataExtracao       0
Ano                0
Mes                0
CanalEntrada       0
Condicao           0
GrupoEconNorm    302
Tipo               0
Servico            0
Modalidade         0
Motivo             0
UF                 0
QtdeSolic          0
dtype: int64

Remova todos os dados ausentes encontrados.

In [ ]:
df = df.loc[:,:].fillna(0)
df.isna().sum().sum()

0

Selecione o serviço que possui o maior número de solicitações QtdeSolic na Anatel.

In [ ]:
df.loc[df.loc[:,'QtdeSolic'] == df.loc[:,'QtdeSolic'].max()]

,DataExtracao,Ano,Mes,CanalEntrada,Condicao,GrupoEconNorm,Tipo,Servico,Modalidade,Motivo,UF,QtdeSolic
139270,2016-04-19,2013,12,Call Center,Nova,OI,Reclamação,Serviço Telefônico Fixo Comutado - STFC,Local,Reparo,MG,4164

Qual é o menor número de solicitações QtdeSolic na Anatel.

In [ ]:
df.loc[:,'QtdeSolic'].min()

1

Mostre todas as linhs iguais ao menor número de solicitações QtdeSolic na Anatel.

In [ ]:
df.loc[df.loc[:,'QtdeSolic'] == df.loc[:,'QtdeSolic'].min()]

,DataExtracao,Ano,Mes,CanalEntrada,Condicao,GrupoEconNorm,Tipo,Servico,Modalidade,Motivo,UF,QtdeSolic
2,2016-04-28,2006,1,Atendimento Pessoal,Nova,NET,Reclamação,Serviço Telefônico Fixo Comutado - STFC,Local,Cobrança,MG,1
3,2016-04-28,2006,1,Atendimento Pessoal,Nova,OI,Reclamação,Móvel Pessoal,Pós-Pago,Serviços Adicionais,MG,1
4,2016-04-28,2006,1,Atendimento Pessoal,Nova,Outros,Reclamação,Móvel Pessoal,Pós-Pago,Clonagem,MG,1
5,2016-04-28,2006,1,Atendimento Pessoal,Reaberta,NET,Reclamação,Serviço Telefônico Fixo Comutado - STFC,Local,Reparo,MG,1
6,2016-04-28,2006,1,Atendimento Pessoal,Reaberta,Outros,Reclamação,Serviço Telefônico Fixo Comutado - STFC,Local,Cancelamento,MG,1
...,...,...,...,...,...,...,...,...,...,...,...,...
509701,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Celular Pré-Pago,Bloqueio ou Suspensão e Desbloqueio,Não consegue desbloquear aparelho,MG,1
509702,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Celular Pré-Pago,Portabilidade,Portabilidade recusada pela prestadora,MG,1
509703,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Celular Pré-Pago,"Qualidade, Funcionamento e Reparo",Não funcionamento de facilidade ou serviço adi...,MG,1
509704,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Telefone Fixo,Cancelamento,Cancelamento de serviço adicional não efetuado,MG,1
509705,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Telefone Fixo,"Qualidade, Funcionamento e Reparo",Linha muda ou sem sinal,MG,1

Mostre as contagens de solicitações QtdeSolic por tipo de serviço Servico.

In [ ]:
df.loc[:, ['QtdeSolic','Servico']].value_counts()

QtdeSolic  Servico
1          TV por Assinatura                          40408
           Celular Pós-Pago                           38066
           Banda Larga Fixa                           29617
           Telefone Fixo                              29136
           Móvel Pessoal                              26838
                                                      ...
307        Celular Pós-Pago                               1
           Celular Pré-Pago                               1
306        Telefone Fixo                                  1
           Serviço Telefônico Fixo Comutado - STFC        1
4164       Serviço Telefônico Fixo Comutado - STFC        1
Length: 3336, dtype: int64

Ao longo dos anos mostre o número de solicitações por mês?

In [ ]:
df.groupby(['Ano', 'Mes']).sum()

          QtdeSolic
Ano  Mes
2006 1         6234
     2         5120
     3         6762
     4         5992
     5         6736
...             ...
2019 5        36407
     6        30322
     7        37336
     8        34473
     9        32696

[165 rows x 1 columns]

Crie o vetor reclamacoes com todos os dados que cuja coluna Tipo seja igual a "Reclamação".

In [ ]:
reclamacoes = df.loc[df.loc[:,'Tipo'] == 'Reclamação']
reclamacoes

,DataExtracao,Ano,Mes,CanalEntrada,Condicao,GrupoEconNorm,Tipo,Servico,Modalidade,Motivo,UF,QtdeSolic
2,2016-04-28,2006,1,Atendimento Pessoal,Nova,NET,Reclamação,Serviço Telefônico Fixo Comutado - STFC,Local,Cobrança,MG,1
3,2016-04-28,2006,1,Atendimento Pessoal,Nova,OI,Reclamação,Móvel Pessoal,Pós-Pago,Serviços Adicionais,MG,1
4,2016-04-28,2006,1,Atendimento Pessoal,Nova,Outros,Reclamação,Móvel Pessoal,Pós-Pago,Clonagem,MG,1
5,2016-04-28,2006,1,Atendimento Pessoal,Reaberta,NET,Reclamação,Serviço Telefônico Fixo Comutado - STFC,Local,Reparo,MG,1
6,2016-04-28,2006,1,Atendimento Pessoal,Reaberta,Outros,Reclamação,Serviço Telefônico Fixo Comutado - STFC,Local,Cancelamento,MG,1
...,...,...,...,...,...,...,...,...,...,...,...,...
509701,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Celular Pré-Pago,Bloqueio ou Suspensão e Desbloqueio,Não consegue desbloquear aparelho,MG,1
509702,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Celular Pré-Pago,Portabilidade,Portabilidade recusada pela prestadora,MG,1
509703,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Celular Pré-Pago,"Qualidade, Funcionamento e Reparo",Não funcionamento de facilidade ou serviço adi...,MG,1
509704,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Telefone Fixo,Cancelamento,Cancelamento de serviço adicional não efetuado,MG,1
509705,2019-10-08,2019,9,Fale Conosco,Reencaminhada,VIVO,Reclamação,Telefone Fixo,"Qualidade, Funcionamento e Reparo",Linha muda ou sem sinal,MG,1

Mostre o número total de solictiações QtdeSolic de reclamações para cada tipo de serviço Servico

In [ ]:
typesReclamacoes = reclamacoes.groupby(['Servico'])['QtdeSolic'].sum()
typesReclamacoes

Servico
Banda Larga Fixa                                            349264
Celular Pré-Pago                                            307646
Celular Pós-Pago                                            812189
Limitado Privado                                                83
Móvel Pessoal                                              1068603
Outros                                                        2230
Radioamador (PY)                                               173
Radiochamada (Paging)                                            1
Radiodifusão (Rádio e TV)                                      203
Rádio do Cidadão (PX)                                          133
Serviço Móvel Aeronáutico                                        9
Serviço Móvel Marítimo                                           3
Serviço Telefônico Fixo Comutado - STFC                     526752
Serviço de Comunicação Multimídia                           239967
Serviço de Rede e Transporte de Telecomunicações - SRTT       2736
Serviços da Anatel                                           24032
TV por Assinatura                                           391773
Telefone Fixo                                               514959
Troncalizado (Trunking)                                       2229
Name: QtdeSolic, dtype: int64

Quais são os maiores ou maior motivo de solicitação de reclamações?

In [ ]:
motivos = typesReclamacoes.loc[(typesReclamacoes == typesReclamacoes.min()) | (typesReclamacoes == typesReclamacoes.max())]

print(f'- Maior motivo: {motivos.keys()[0]}')
print(f'- Menor motivo: {motivos.keys()[1]}')

- Maior motivo: Móvel Pessoal
- Menor motivo: Radiochamada (Paging)

Faça um agrupamento de dados pela coluna GrupoEconNorm, mostrando um sumário estatístico da quantidade solicitações QtdeSolic.

In [ ]:
df.groupby(['GrupoEconNorm'])['QtdeSolic'].describe()

,count,mean,std,min,25%,50%,75%,max
GrupoEconNorm,,,,,,,,
0,302.0,1.344371,0.950931,1.0,1.00,1.0,1.00,9.0
ALGAR,31030.0,3.074670,7.476908,1.0,1.00,1.0,2.00,259.0
Anatel,22833.0,2.537993,4.659411,1.0,1.00,1.0,2.00,128.0
BLUE,3105.0,1.616747,1.473557,1.0,1.00,1.0,2.00,18.0
Brisanet,5.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0
CABO TELECOM,1.0,1.000000,NaN,1.0,1.00,1.0,1.00,1.0
CLARO,56270.0,7.248623,34.269337,1.0,1.00,2.0,4.00,1291.0
Correios Celular,258.0,1.131783,0.438956,1.0,1.00,1.0,1.00,4.0
Datora,2.0,1.500000,0.707107,1.0,1.25,1.5,1.75,2.0
EMBRATEL,1425.0,2.041404,2.697345,1.0,1.00,1.0,2.00,26.0
GVT,6398.0,6.092685,19.560634,1.0,1.00,2.0,4.00,666.0
HUGHES NET,399.0,1.358396,0.829345,1.0,1.00,1.0,1.00,6.0
Intelig,228.0,1.381579,0.817762,1.0,1.00,1.0,1.25,6.0
NET,51631.0,4.981058,13.085830,1.0,1.00,2.0,4.00,350.0
NEXTEL,3198.0,2.069418,3.907220,1.0,1.00,1.0,2.00,52.0
NOSSA TV - BRASIL,12.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0
OI,133068.0,13.773822,72.673658,1.0,1.00,2.0,6.00,4164.0
Outros,23898.0,4.035066,11.371657,1.0,1.00,1.0,3.00,286.0
SERCOMTEL,60.0,1.016667,0.129099,1.0,1.00,1.0,1.00,2.0
SKY,24332.0,6.754028,22.213154,1.0,1.00,2.0,5.00,474.0
TIM,66568.0,10.462760,37.195234,1.0,1.00,2.0,7.00,1364.0
VIVO,84683.0,7.715551,36.086811,1.0,1.00,2.0,5.00,1624.0